/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2023-08-06 11:50:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>JSP Page</title>\n");
      out.write("\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("\n");
      out.write("        <nav class=\"navbar navbar-expand-sm navbar-dark bg-dark\">\n");
      out.write("            <div class=\"container-fluid\">\n");
      out.write("                <a class=\"navbar-brand\" href=\"javascript:void(0)\">Work</a>\n");
      out.write("                <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#mynavbar\">\n");
      out.write("                    <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("                </button>\n");
      out.write("                <div class=\"collapse navbar-collapse\" id=\"mynavbar\">\n");
      out.write("                    <ul class=\"navbar-nav me-auto\">\n");
      out.write("                        <li class=\"nav-item\">\n");
      out.write("                            <a class=\"nav-link\" href=\"javascript:void(0)\">Trang chủ</a>\n");
      out.write("                        </li>\n");
      out.write("                        <li class=\"nav-item\">\n");
      out.write("                            <a class=\"nav-link\" href=\"javascript:void(0)\">Hồ sơ</a>\n");
      out.write("                        </li>\n");
      out.write("                        <li class=\"nav-item\">\n");
      out.write("                            <a class=\"nav-link\" href=\"javascript:void(0)\">Đăng ký</a>\n");
      out.write("                        </li>\n");
      out.write("                         <li class=\"nav-item\">\n");
      out.write("                            <a class=\"nav-link\" href=\"javascript:void(0)\">Đăng nhập</a>\n");
      out.write("                        </li>\n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </nav>\n");
      out.write("        \n");
      out.write("                <nav class=\"navbar navbar-expand-sm navbar-dark bg-dark\">\n");
      out.write("            <div class=\"container-fluid\">\n");
      out.write("                <a class=\"navbar-brand\" href=\"javascript:void(0)\">Work</a>\n");
      out.write("                <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#mynavbar\">\n");
      out.write("                    <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("                </button>\n");
      out.write("                <div class=\"collapse navbar-collapse\" id=\"mynavbar\">\n");
      out.write("                    <ul class=\"navbar-nav me-auto\">\n");
      out.write("                        <li class=\"nav-item\">\n");
      out.write("                            <a class=\"nav-link\" href=\"javascript:void(0)\">Trang chủ</a>\n");
      out.write("                        </li>\n");
      out.write("                        <li class=\"nav-item\">\n");
      out.write("                            <a class=\"nav-link\" href=\"javascript:void(0)\">Đăng tin tuyển dụng</a>\n");
      out.write("                        </li>\n");
      out.write("                        <li class=\"nav-item\">\n");
      out.write("                            <a class=\"nav-link\" href=\"javascript:void(0)\">Đánh giá</a>\n");
      out.write("                        </li>\n");
      out.write("                         <li class=\"nav-item\">\n");
      out.write("                            <a class=\"nav-link\" href=\"javascript:void(0)\">Tìm ứng viên</a>\n");
      out.write("                        </li>\n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </nav>\n");
      out.write("        \n");
      out.write("                        <nav class=\"navbar navbar-expand-sm navbar-dark bg-dark\">\n");
      out.write("            <div class=\"container-fluid\">\n");
      out.write("                <a class=\"navbar-brand\" href=\"javascript:void(0)\">Work</a>\n");
      out.write("                <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#mynavbar\">\n");
      out.write("                    <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("                </button>\n");
      out.write("                <div class=\"collapse navbar-collapse\" id=\"mynavbar\">\n");
      out.write("                    <ul class=\"navbar-nav me-auto\">\n");
      out.write("                        <li class=\"nav-item\">\n");
      out.write("                            <a class=\"nav-link\" href=\"javascript:void(0)\">Trang chủ</a>\n");
      out.write("                        </li>\n");
      out.write("                        <li class=\"nav-item\">\n");
      out.write("                            <a class=\"nav-link\" href=\"javascript:void(0)\">Thống kê</a>\n");
      out.write("                        </li>\n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </nav>\n");
      out.write("\n");
      out.write("        <ul class=\"nav nav-pills\" style = \"background-color : cornflowerblue \" >\n");
      out.write("            <li class=\"nav-item\">\n");
      out.write("                <div class=\"nav-link\" style=\"background-color: greenyellow\">\n");
      out.write("                    <img src=\"https://img.icons8.com/?size=512&id=h75QzKozczfv&format=png\" style=\" height :30px\">\n");
      out.write("                    <a style = \" color: darkmagenta ; font-size: 20px ; font-weight: 900\" >\n");
      out.write("                        Lọc\n");
      out.write("                    </a>\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("            </li>\n");
      out.write("            <li class=\"nav-item dropdown\">\n");
      out.write("                <div class=\"nav-link dropdown-toggle\" data-bs-toggle=\"dropdown\">\n");
      out.write("                    <img src=\"https://img.icons8.com/?size=1x&id=Fed3w16hj37u&format=png\" style=\" height :30px\">\n");
      out.write("                    <a href=\"#\" style=\"text-decoration: none  ; color: linen ; font-size: 20px ; font-weight: 700\" >\n");
      out.write("                        Thành phố\n");
      out.write("                    </a>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"#\">Link 1</a></li>\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"#\">Link 2</a></li>\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"#\">Link 3</a></li>\n");
      out.write("                        <li><a class=\"dropdown-item-text\" href=\"#\">Text Link</a></li>\n");
      out.write("                        <li><span class=\"dropdown-item-text\">Just Text</span></li>\n");
      out.write("                    </ul>\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("            </li>\n");
      out.write("            <li class=\"nav-item dropdown\" >\n");
      out.write("                <div class=\"nav-link dropdown-toggle\" data-bs-toggle=\"dropdown\">\n");
      out.write("                    <img src=\"https://img.icons8.com/?size=512&id=qSDZIF4neVDE&format=png\" style=\" height :30px\">\n");
      out.write("                    <a href=\"#\" style=\"text-decoration: none  ; color: linen ; font-size: 20px;font-weight: 700\" >\n");
      out.write("                        Quận\n");
      out.write("                    </a>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"#\">Link 1</a></li>\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"#\">Link 2</a></li>\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"#\">Link 3</a></li>\n");
      out.write("                        <li><a class=\"dropdown-item-text\" href=\"#\">Text Link</a></li>\n");
      out.write("                        <li><span class=\"dropdown-item-text\">Just Text</span></li>\n");
      out.write("                    </ul>\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("            </li>\n");
      out.write("            <li class=\"nav-item dropdown\" >\n");
      out.write("                <div class=\"nav-link dropdown-toggle\" data-bs-toggle=\"dropdown\">\n");
      out.write("                    <img src=\"https://img.icons8.com/?size=512&id=ScAViD0I8h4B&format=png\" style=\" height :30px\">\n");
      out.write("                    <a href=\"#\" style=\"text-decoration: none  ; color: linen ; font-size: 20px;font-weight: 700\" >\n");
      out.write("                        Nghề nghiệp\n");
      out.write("                    </a>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"#\">Link 1</a></li>\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"#\">Link 2</a></li>\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"#\">Link 3</a></li>\n");
      out.write("                        <li><a class=\"dropdown-item-text\" href=\"#\">Text Link</a></li>\n");
      out.write("                        <li><span class=\"dropdown-item-text\">Just Text</span></li>\n");
      out.write("                    </ul>\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("            </li>\n");
      out.write("            <li class=\"nav-item dropdown\">\n");
      out.write("                <div class=\"nav-link dropdown-toggle\" data-bs-toggle=\"dropdown\">\n");
      out.write("                    <img src=\"https://img.icons8.com/?size=512&id=70052&format=png\" style=\" height :30px\">\n");
      out.write("                    <a href=\"#\" style=\"text-decoration: none  ; color: linen ; font-size: 20px;font-weight: 700\" >\n");
      out.write("                        Tuổi\n");
      out.write("                    </a>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"#\"> tuổi <= 18 </a></li>\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"#\">18 <= tuổi <= 30</a></li>\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"#\"> tuổi >= 30 </a></li>\n");
      out.write("                    </ul>\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("            </li>\n");
      out.write("            <li class=\"nav-item dropdown\" >\n");
      out.write("                <div class=\"nav-link dropdown-toggle\" data-bs-toggle=\"dropdown\">\n");
      out.write("                    <img src=\"https://img.icons8.com/?size=512&id=LVPdJpaboyzj&format=png\" style=\" height :30px\">\n");
      out.write("                    <a href=\"#\" style=\"text-decoration: none  ; color: linen ; font-size: 20px;font-weight: 700\" >\n");
      out.write("                        Kinh nghiệm\n");
      out.write("                    </a>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"#\">Link 1</a></li>\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"#\">Link 2</a></li>\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"#\">Link 3</a></li>\n");
      out.write("                        <li><a class=\"dropdown-item-text\" href=\"#\">Text Link</a></li>\n");
      out.write("                        <li><span class=\"dropdown-item-text\">Just Text</span></li>\n");
      out.write("                    </ul>\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("            </li>\n");
      out.write("            <li class=\"nav-item dropdown\" >\n");
      out.write("                <div class=\"nav-link dropdown-toggle\" data-bs-toggle=\"dropdown\">\n");
      out.write("                    <img src=\"https://img.icons8.com/?size=512&id=11225&format=png\" style=\" height :30px\">\n");
      out.write("                    <a href=\"#\" style=\"text-decoration: none  ; color: linen ; font-size: 20px;font-weight: 700\" >\n");
      out.write("                        Học vấn\n");
      out.write("                    </a>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"#\">Link 1</a></li>\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"#\">Link 2</a></li>\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"#\">Link 3</a></li>\n");
      out.write("                        <li><a class=\"dropdown-item-text\" href=\"#\">Text Link</a></li>\n");
      out.write("                        <li><span class=\"dropdown-item-text\">Just Text</span></li>\n");
      out.write("                    </ul>\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("            </li>\n");
      out.write("            <li style=\"margin:auto ; width: 350px\">\n");
      out.write("                <form class=\"d-flex\">\n");
      out.write("                    <input class=\"form-control me-auto\" type=\"text\" placeholder=\"Nhập tên công ty cần tìm .....\">\n");
      out.write("                </form>\n");
      out.write("            </li>\n");
      out.write("        </ul>\n");
      out.write("\n");
      out.write("        ");
      out.write("\n");
      out.write("        <ul class=\"nav nav-pills\" style = \"background-color : cornflowerblue \" >\n");
      out.write("            <li class=\"nav-item\">\n");
      out.write("                <div class=\"nav-link\" style=\"background-color: greenyellow\">\n");
      out.write("                    <img src=\"https://img.icons8.com/?size=512&id=h75QzKozczfv&format=png\" style=\" height :30px\">\n");
      out.write("                    <a style = \" color: darkmagenta ; font-size: 20px ; font-weight: 900\" >\n");
      out.write("                        Lọc\n");
      out.write("                    </a>\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("            </li>\n");
      out.write("            <li class=\"nav-item dropdown\">\n");
      out.write("                <div class=\"nav-link dropdown-toggle\" data-bs-toggle=\"dropdown\">\n");
      out.write("                    <img src=\"https://img.icons8.com/?size=1x&id=Fed3w16hj37u&format=png\" style=\" height :30px\">\n");
      out.write("                    <a href=\"#\" style=\"text-decoration: none  ; color: linen ; font-size: 20px ; font-weight: 700\" >\n");
      out.write("                        Thành phố\n");
      out.write("                    </a>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"#\">Link 1</a></li>\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"#\">Link 2</a></li>\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"#\">Link 3</a></li>\n");
      out.write("                        <li><a class=\"dropdown-item-text\" href=\"#\">Text Link</a></li>\n");
      out.write("                        <li><span class=\"dropdown-item-text\">Just Text</span></li>\n");
      out.write("                    </ul>\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("            </li>\n");
      out.write("            <li class=\"nav-item dropdown\" >\n");
      out.write("                <div class=\"nav-link dropdown-toggle\" data-bs-toggle=\"dropdown\">\n");
      out.write("                    <img src=\"https://img.icons8.com/?size=512&id=qSDZIF4neVDE&format=png\" style=\" height :30px\">\n");
      out.write("                    <a href=\"#\" style=\"text-decoration: none  ; color: linen ; font-size: 20px;font-weight: 700\" >\n");
      out.write("                        Quận\n");
      out.write("                    </a>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"#\">Link 1</a></li>\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"#\">Link 2</a></li>\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"#\">Link 3</a></li>\n");
      out.write("                        <li><a class=\"dropdown-item-text\" href=\"#\">Text Link</a></li>\n");
      out.write("                        <li><span class=\"dropdown-item-text\">Just Text</span></li>\n");
      out.write("                    </ul>\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("            </li>\n");
      out.write("            <li class=\"nav-item dropdown\" >\n");
      out.write("                <div class=\"nav-link dropdown-toggle\" data-bs-toggle=\"dropdown\">\n");
      out.write("                    <img src=\"https://img.icons8.com/?size=512&id=ScAViD0I8h4B&format=png\" style=\" height :30px\">\n");
      out.write("                    <a href=\"#\" style=\"text-decoration: none  ; color: linen ; font-size: 20px;font-weight: 700\" >\n");
      out.write("                        Nghề nghiệp\n");
      out.write("                    </a>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"#\">Link 1</a></li>\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"#\">Link 2</a></li>\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"#\">Link 3</a></li>\n");
      out.write("                        <li><a class=\"dropdown-item-text\" href=\"#\">Text Link</a></li>\n");
      out.write("                        <li><span class=\"dropdown-item-text\">Just Text</span></li>\n");
      out.write("                    </ul>\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("            </li>\n");
      out.write("            <li class=\"nav-item dropdown\">\n");
      out.write("                <div class=\"nav-link dropdown-toggle\" data-bs-toggle=\"dropdown\">\n");
      out.write("                    <img src=\"https://img.icons8.com/?size=512&id=9489&format=png\" style=\" height :30px\">\n");
      out.write("                    <a href=\"#\" style=\"text-decoration: none  ; color: linen ; font-size: 20px;font-weight: 700\" >\n");
      out.write("                        Hình thức\n");
      out.write("                    </a>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"#\">Link 1</a></li>\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"#\">Link 2</a></li>\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"#\">Link 3</a></li>\n");
      out.write("                        <li><a class=\"dropdown-item-text\" href=\"#\">Text Link</a></li>\n");
      out.write("                        <li><span class=\"dropdown-item-text\">Just Text</span></li>\n");
      out.write("                    </ul>\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("            </li>\n");
      out.write("            <li class=\"nav-item dropdown\" >\n");
      out.write("                <div class=\"nav-link dropdown-toggle\" data-bs-toggle=\"dropdown\">\n");
      out.write("                    <img src=\"https://img.icons8.com/?size=512&id=11225&format=png\" style=\" height :30px\">\n");
      out.write("                    <a href=\"#\" style=\"text-decoration: none  ; color: linen ; font-size: 20px;font-weight: 700\" >\n");
      out.write("                        Học vấn\n");
      out.write("                    </a>\n");
      out.write("                    <ul class=\"dropdown-menu\">\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"#\">Link 1</a></li>\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"#\">Link 2</a></li>\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"#\">Link 3</a></li>\n");
      out.write("                        <li><a class=\"dropdown-item-text\" href=\"#\">Text Link</a></li>\n");
      out.write("                        <li><span class=\"dropdown-item-text\">Just Text</span></li>\n");
      out.write("                    </ul>\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("            </li>\n");
      out.write("            <li style=\"margin:auto ; width: 550px\">\n");
      out.write("                <form class=\"d-flex\">\n");
      out.write("                    <input class=\"form-control me-auto\" type=\"text\" placeholder=\"Nhập tên công ty cần tìm .....\">\n");
      out.write("                </form>\n");
      out.write("            </li>\n");
      out.write("        </ul>\n");
      out.write("\n");
      out.write("<div class=\"container mt-3\">\n");
      out.write("  <h2>Textarea</h2>\n");
      out.write("  <p>Use the .form-control class to style textareas as well:</p>\n");
      out.write("  <form action=\"/action_page.php\">\n");
      out.write("    <div class=\"mb-3 mt-3\">\n");
      out.write("      <label for=\"comment\">Comments:</label>\n");
      out.write("      <textarea class=\"form-control\" rows=\"5\" id=\"comment\" name=\"text\"></textarea>\n");
      out.write("    </div>\n");
      out.write("    <button type=\"submit\" class=\"btn btn-primary\">Submit</button>\n");
      out.write("  </form>\n");
      out.write("</div>\n");
      out.write("        \n");
      out.write("        <div class=\"form-check\">\n");
      out.write("  <input type=\"radio\" class=\"form-check-input\" id=\"radio1\" name=\"optradio\" value=\"option1\" checked>Option 1\n");
      out.write("  <label class=\"form-check-label\" for=\"radio1\"></label>\n");
      out.write("</div>\n");
      out.write("<div class=\"form-check\">\n");
      out.write("  <input type=\"radio\" class=\"form-check-input\" id=\"radio2\" name=\"optradio\" value=\"option2\">Option 2\n");
      out.write("  <label class=\"form-check-label\" for=\"radio2\"></label>\n");
      out.write("</div>\n");
      out.write("<div class=\"form-check\">\n");
      out.write("  <input type=\"radio\" class=\"form-check-input\" disabled>Option 3\n");
      out.write("  <label class=\"form-check-label\"></label>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("    </body>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
